//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lux.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LuxParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILuxVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] LuxParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LuxParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStat([NotNull] LuxParser.EmptyStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStat([NotNull] LuxParser.AssignStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionCallStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallStat([NotNull] LuxParser.FunctionCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewStat([NotNull] LuxParser.NewStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IncDecStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncDecStat_([NotNull] LuxParser.IncDecStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LabelStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelStat([NotNull] LuxParser.LabelStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStat([NotNull] LuxParser.BreakStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStat([NotNull] LuxParser.ContinueStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GotoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStat([NotNull] LuxParser.GotoStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferStat_([NotNull] LuxParser.DeferStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GuardStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuardStat_([NotNull] LuxParser.GuardStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStat([NotNull] LuxParser.DoStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStat([NotNull] LuxParser.WhileStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RepeatStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatStat([NotNull] LuxParser.RepeatStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat_([NotNull] LuxParser.IfStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericForStat([NotNull] LuxParser.NumericForStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GenericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericForStat([NotNull] LuxParser.GenericForStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclStat([NotNull] LuxParser.FunctionDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LocalFunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalFunctionDeclStat([NotNull] LuxParser.LocalFunctionDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LocalDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalDeclStat([NotNull] LuxParser.LocalDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EnumDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclStat([NotNull] LuxParser.EnumDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStat_([NotNull] LuxParser.ImportStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportStat_([NotNull] LuxParser.ExportStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStat_([NotNull] LuxParser.DeclareStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatchStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchStat_([NotNull] LuxParser.MatchStat_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclStat([NotNull] LuxParser.ClassDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclStat([NotNull] LuxParser.InterfaceDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExtendDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendDeclStat([NotNull] LuxParser.ExtendDeclStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuperCallStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperCallStat([NotNull] LuxParser.SuperCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.doBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoBlock([NotNull] LuxParser.DoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileLoop([NotNull] LuxParser.WhileLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.repeatLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatLoop([NotNull] LuxParser.RepeatLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStat([NotNull] LuxParser.IfStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.elseIfClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfClause([NotNull] LuxParser.ElseIfClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseClause([NotNull] LuxParser.ElseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.numericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericFor([NotNull] LuxParser.NumericForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.genericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericFor([NotNull] LuxParser.GenericForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] LuxParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncStat([NotNull] LuxParser.PostIncStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecStat([NotNull] LuxParser.PostDecStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreIncStat([NotNull] LuxParser.PreIncStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreDecStat([NotNull] LuxParser.PreDecStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferCallStat</c>
	/// labeled alternative in <see cref="LuxParser.deferStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferCallStat([NotNull] LuxParser.DeferCallStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeferBlockStat</c>
	/// labeled alternative in <see cref="LuxParser.deferStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeferBlockStat([NotNull] LuxParser.DeferBlockStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.guardStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuardStat([NotNull] LuxParser.GuardStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStat([NotNull] LuxParser.ReturnStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDecl([NotNull] LuxParser.FunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.localFunctionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalFunctionDecl([NotNull] LuxParser.LocalFunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.localDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalDecl([NotNull] LuxParser.LocalDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.annotationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationList([NotNull] LuxParser.AnnotationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] LuxParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.annotationArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationArgList([NotNull] LuxParser.AnnotationArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedAnnotationArg</c>
	/// labeled alternative in <see cref="LuxParser.annotationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedAnnotationArg([NotNull] LuxParser.NamedAnnotationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PositionalAnnotationArg</c>
	/// labeled alternative in <see cref="LuxParser.annotationArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositionalAnnotationArg([NotNull] LuxParser.PositionalAnnotationArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportFrom</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportFrom([NotNull] LuxParser.ImportFromContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportSideEffect</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportSideEffect([NotNull] LuxParser.ImportSideEffectContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedImport([NotNull] LuxParser.NamedImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DefaultImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefaultImport([NotNull] LuxParser.DefaultImportContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamespaceImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceImport([NotNull] LuxParser.NamespaceImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.importName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportName([NotNull] LuxParser.ImportNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDecl([NotNull] LuxParser.EnumDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumMember([NotNull] LuxParser.EnumMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] LuxParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassFieldMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassFieldMember([NotNull] LuxParser.ClassFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassMethodMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMethodMember([NotNull] LuxParser.ClassMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassAbstractMethodMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAbstractMethodMember([NotNull] LuxParser.ClassAbstractMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassConstructorMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassConstructorMember([NotNull] LuxParser.ClassConstructorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassOperatorMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOperatorMember([NotNull] LuxParser.ClassOperatorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ClassAccessorMember</c>
	/// labeled alternative in <see cref="LuxParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassAccessorMember([NotNull] LuxParser.ClassAccessorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymPlus</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymPlus([NotNull] LuxParser.OpSymPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymMinus</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymMinus([NotNull] LuxParser.OpSymMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymStar</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymStar([NotNull] LuxParser.OpSymStarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymSlash</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymSlash([NotNull] LuxParser.OpSymSlashContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymDSlash</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymDSlash([NotNull] LuxParser.OpSymDSlashContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymPercent</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymPercent([NotNull] LuxParser.OpSymPercentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymCaret</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymCaret([NotNull] LuxParser.OpSymCaretContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymConcat</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymConcat([NotNull] LuxParser.OpSymConcatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymEq</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymEq([NotNull] LuxParser.OpSymEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymLt</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymLt([NotNull] LuxParser.OpSymLtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymLte</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymLte([NotNull] LuxParser.OpSymLteContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OpSymHash</c>
	/// labeled alternative in <see cref="LuxParser.operatorSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpSymHash([NotNull] LuxParser.OpSymHashContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDecl([NotNull] LuxParser.InterfaceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.typeParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParamList([NotNull] LuxParser.TypeParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.typeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParam([NotNull] LuxParser.TypeParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.classRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassRef([NotNull] LuxParser.ClassRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceFieldMember</c>
	/// labeled alternative in <see cref="LuxParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceFieldMember([NotNull] LuxParser.InterfaceFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceDefaultMethodMember</c>
	/// labeled alternative in <see cref="LuxParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDefaultMethodMember([NotNull] LuxParser.InterfaceDefaultMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterfaceMethodMember</c>
	/// labeled alternative in <see cref="LuxParser.interfaceMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceMethodMember([NotNull] LuxParser.InterfaceMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.extendDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendDecl([NotNull] LuxParser.ExtendDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.extendMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendMethod([NotNull] LuxParser.ExtendMethodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportFunction([NotNull] LuxParser.ExportFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportLocalFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportLocalFunction([NotNull] LuxParser.ExportLocalFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportLocal</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportLocal([NotNull] LuxParser.ExportLocalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportEnum</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportEnum([NotNull] LuxParser.ExportEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportClass</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportClass([NotNull] LuxParser.ExportClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportInterface</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportInterface([NotNull] LuxParser.ExportInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.matchStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchStat([NotNull] LuxParser.MatchStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.matchExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExpr([NotNull] LuxParser.MatchExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.matchArm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchArm([NotNull] LuxParser.MatchArmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.matchExprArm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExprArm([NotNull] LuxParser.MatchExprArmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BindingPattern</c>
	/// labeled alternative in <see cref="LuxParser.matchPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingPattern([NotNull] LuxParser.BindingPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValuePattern</c>
	/// labeled alternative in <see cref="LuxParser.matchPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuePattern([NotNull] LuxParser.ValuePatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.declareStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStat([NotNull] LuxParser.DeclareStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareFunction([NotNull] LuxParser.DeclareFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareVariable([NotNull] LuxParser.DeclareVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareModule</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareModule([NotNull] LuxParser.DeclareModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareEnum([NotNull] LuxParser.DeclareEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClass</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClass([NotNull] LuxParser.DeclareClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareInterface</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareInterface([NotNull] LuxParser.DeclareInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassFieldMember</c>
	/// labeled alternative in <see cref="LuxParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassFieldMember([NotNull] LuxParser.DeclareClassFieldMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassMethodMember</c>
	/// labeled alternative in <see cref="LuxParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassMethodMember([NotNull] LuxParser.DeclareClassMethodMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassConstructorMember</c>
	/// labeled alternative in <see cref="LuxParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassConstructorMember([NotNull] LuxParser.DeclareClassConstructorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassOperatorMember</c>
	/// labeled alternative in <see cref="LuxParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassOperatorMember([NotNull] LuxParser.DeclareClassOperatorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclareClassAccessorMember</c>
	/// labeled alternative in <see cref="LuxParser.declareClassMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareClassAccessorMember([NotNull] LuxParser.DeclareClassAccessorMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.funcSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncSignature([NotNull] LuxParser.FuncSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PredicateReturn</c>
	/// labeled alternative in <see cref="LuxParser.funcReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicateReturn([NotNull] LuxParser.PredicateReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PlainReturn</c>
	/// labeled alternative in <see cref="LuxParser.funcReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlainReturn([NotNull] LuxParser.PlainReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.declareModuleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareModuleBlock([NotNull] LuxParser.DeclareModuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.declareEnumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareEnumMember([NotNull] LuxParser.DeclareEnumMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareFunction([NotNull] LuxParser.ModuleDeclareFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareVariable([NotNull] LuxParser.ModuleDeclareVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareEnum([NotNull] LuxParser.ModuleDeclareEnumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareClass</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareClass([NotNull] LuxParser.ModuleDeclareClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModuleDeclareInterface</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclareInterface([NotNull] LuxParser.ModuleDeclareInterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncName([NotNull] LuxParser.FuncNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncBody([NotNull] LuxParser.FuncBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParamListWithNames</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamListWithNames([NotNull] LuxParser.ParamListWithNamesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParamListVararg</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamListVararg([NotNull] LuxParser.ParamListVarargContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] LuxParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.varargParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarargParam([NotNull] LuxParser.VarargParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarList([NotNull] LuxParser.VarListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameList([NotNull] LuxParser.NameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.attribNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribNameList([NotNull] LuxParser.AttribNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribName([NotNull] LuxParser.AttribNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrib([NotNull] LuxParser.AttribContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] LuxParser.ExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.typeAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAnnotation([NotNull] LuxParser.TypeAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnionType</c>
	/// labeled alternative in <see cref="LuxParser.typeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionType([NotNull] LuxParser.UnionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostfixType</c>
	/// labeled alternative in <see cref="LuxParser.typeSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixType([NotNull] LuxParser.PostfixTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArraySuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySuffix([NotNull] LuxParser.ArraySuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullableSuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullableSuffix([NotNull] LuxParser.NullableSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilType([NotNull] LuxParser.NilTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BareFunctionType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBareFunctionType([NotNull] LuxParser.BareFunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedType([NotNull] LuxParser.NamedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncType([NotNull] LuxParser.FuncTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableType_</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableType_([NotNull] LuxParser.TableType_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GroupedOrTupleType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupedOrTupleType([NotNull] LuxParser.GroupedOrTupleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariadicType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariadicType([NotNull] LuxParser.VariadicTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.typeArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgList([NotNull] LuxParser.TypeArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConcreteTypeArg</c>
	/// labeled alternative in <see cref="LuxParser.typeArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcreteTypeArg([NotNull] LuxParser.ConcreteTypeArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WildcardTypeArg</c>
	/// labeled alternative in <see cref="LuxParser.typeArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcardTypeArg([NotNull] LuxParser.WildcardTypeArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionType([NotNull] LuxParser.FunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeList([NotNull] LuxParser.TypeListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyTableType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyTableType([NotNull] LuxParser.EmptyTableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapType([NotNull] LuxParser.MapTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StructType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructType([NotNull] LuxParser.StructTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructField([NotNull] LuxParser.StructFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreIncExpr([NotNull] LuxParser.PreIncExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOrExpr([NotNull] LuxParser.BitwiseOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ComparisonExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpr([NotNull] LuxParser.ComparisonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeCheckExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCheckExpr([NotNull] LuxParser.TypeCheckExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionDefExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefExpr([NotNull] LuxParser.FunctionDefExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PreDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreDecExpr([NotNull] LuxParser.PreDecExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpr([NotNull] LuxParser.LogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NonNilAssertExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonNilAssertExpr([NotNull] LuxParser.NonNilAssertExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFalseLiteral([NotNull] LuxParser.FalseLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplicativeExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] LuxParser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalOrExpr([NotNull] LuxParser.AltLogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrueLiteral([NotNull] LuxParser.TrueLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostIncExpr([NotNull] LuxParser.PostIncExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuperCallExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuperCallExpr([NotNull] LuxParser.SuperCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilCoalesceExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilCoalesceExpr([NotNull] LuxParser.NilCoalesceExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostDecExpr([NotNull] LuxParser.PostDecExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitShiftExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitShiftExpr([NotNull] LuxParser.BitShiftExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAndExpr([NotNull] LuxParser.BitwiseAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalNotExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalNotExpr([NotNull] LuxParser.AltLogicalNotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltLogicalAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltLogicalAndExpr([NotNull] LuxParser.AltLogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] LuxParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstanceOfExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceOfExpr([NotNull] LuxParser.InstanceOfExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixExpr([NotNull] LuxParser.PrefixExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeOfExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfExpr([NotNull] LuxParser.TypeOfExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpr([NotNull] LuxParser.PowerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConcatExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatExpr([NotNull] LuxParser.ConcatExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpr([NotNull] LuxParser.LogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AwaitExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwaitExpr([NotNull] LuxParser.AwaitExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] LuxParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AdditiveExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] LuxParser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarargExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarargExpr([NotNull] LuxParser.VarargExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NilLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNilLiteral([NotNull] LuxParser.NilLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpr([NotNull] LuxParser.NewExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseXorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseXorExpr([NotNull] LuxParser.BitwiseXorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] LuxParser.NumberLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeCastExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCastExpr([NotNull] LuxParser.TypeCastExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableConstructorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableConstructorExpr([NotNull] LuxParser.TableConstructorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatchExprExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExprExpr([NotNull] LuxParser.MatchExprExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLtOp([NotNull] LuxParser.LtOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGtOp([NotNull] LuxParser.GtOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLteOp([NotNull] LuxParser.LteOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGteOp([NotNull] LuxParser.GteOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NeqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNeqOp([NotNull] LuxParser.NeqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AltNeqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltNeqOp([NotNull] LuxParser.AltNeqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqOp([NotNull] LuxParser.EqOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLshiftOp([NotNull] LuxParser.LshiftOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRshiftOp([NotNull] LuxParser.RshiftOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOp([NotNull] LuxParser.AddOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SubOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubOp([NotNull] LuxParser.SubOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulOp([NotNull] LuxParser.MulOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivOp([NotNull] LuxParser.DivOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FloorDivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloorDivOp([NotNull] LuxParser.FloorDivOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ModOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModOp([NotNull] LuxParser.ModOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalNotOp([NotNull] LuxParser.LogicalNotOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LengthOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLengthOp([NotNull] LuxParser.LengthOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegateOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegateOp([NotNull] LuxParser.NegateOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseNotOp([NotNull] LuxParser.BitwiseNotOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.prefixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixExp([NotNull] LuxParser.PrefixExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameVarOrExp([NotNull] LuxParser.NameVarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenVarOrExp([NotNull] LuxParser.ParenVarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotSuffix([NotNull] LuxParser.DotSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptDotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptDotSuffix([NotNull] LuxParser.OptDotSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexSuffix([NotNull] LuxParser.IndexSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallSuffix([NotNull] LuxParser.MethodCallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallSuffix([NotNull] LuxParser.CallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptCallSuffix([NotNull] LuxParser.OptCallSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameVar([NotNull] LuxParser.NameVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FieldVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldVar([NotNull] LuxParser.FieldVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexVar([NotNull] LuxParser.IndexVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DirectCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectCall([NotNull] LuxParser.DirectCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MethodCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] LuxParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenArgs([NotNull] LuxParser.ParenArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TableArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableArgs([NotNull] LuxParser.TableArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringArgs([NotNull] LuxParser.StringArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDef([NotNull] LuxParser.FunctionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.tableConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableConstructor([NotNull] LuxParser.TableConstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldList([NotNull] LuxParser.FieldListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BracketField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketField([NotNull] LuxParser.BracketFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameField([NotNull] LuxParser.NameFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionField([NotNull] LuxParser.FunctionFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueField([NotNull] LuxParser.ValueFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuxParser.fieldSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldSep([NotNull] LuxParser.FieldSepContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLit([NotNull] LuxParser.IntLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexLit([NotNull] LuxParser.HexLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLit([NotNull] LuxParser.FloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexFloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexFloatLit([NotNull] LuxParser.HexFloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleQuotedStr([NotNull] LuxParser.DoubleQuotedStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleQuotedStr([NotNull] LuxParser.SingleQuotedStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LongStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongStr([NotNull] LuxParser.LongStrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InterpolatedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolatedStr([NotNull] LuxParser.InterpolatedStrContext context);
}
