namespace Nebra.Diagnostics;

/// <summary>
/// The diagnostic category is used to categorize diagnostics. It is used to group diagnostics together into specific
/// parts of the compilation process.
/// </summary>
public enum DiagnosticCategory
{
    /// <summary>
    /// Shouldn't be used, this is used for diagnostics that don't fit into any of the other categories.
    /// This maybe used for diagnostics that are generated by external tools or libraries that don't have a specific
    /// category or aren't categorized yet.
    /// </summary>
    Unknown,
    /// <summary>
    /// Internal diagnostics are diagnostics that happen because of an error in the compiler itself.
    /// These diagnostics are not caused by the user's code and should not be reported to the user.
    /// </summary>
    Internal,
    /// <summary>
    /// Syntax diagnostics are diagnostics that happen because of a syntax error in the user's code.
    /// </summary>
    Syntax,
    /// <summary>
    /// Type diagnostics are diagnostics that happen because of a type error in the user's code.
    /// </summary>
    Type,
    /// <summary>
    /// Semantic diagnostics are diagnostics that happen because of a semantic error in the user's code. <see cref="Type"/>
    /// diagnostics are a subset of semantic diagnostics, but semantic diagnostics can also include other types of
    /// errors that are not strictly type errors, such as name resolution errors, accessibility errors, etc.
    /// </summary>
    Semantic,
}